### ISSUE TITLE
Do you allow using this code under the AGPLv3 license ?

### ISSUE THREAD

**Issue by Ammar64** [SethClydesdale/browser-pong#1]
> The GPL licenses (including LGPL and AGPL) require that the entire application is distributed under the terms of the GPL license. In principle, this is incompatible with the MPL license, but the MPL-2.0 license has a special exception for allowing the code to be distributed under the terms of the GPL licenses. However, an author can also choose to explicitly disable that exception.

Can I use this code under AGPLv3 ?  
I want to include this as a secret game in my app. Thanks

**Comment by SethClydesdale** [comment]
Hello!

As long as you include credit in any form you like (my name, repo link, etc.), there's no problem. I'd be honored, so feel free!

**Comment by Ammar64** [comment]
Thanks.
